services:
  - type: web
    name: kemp-shop
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kempbd
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        value: dqadgdsi3
      - key: CLOUDINARY_API_KEY
        value: 215913894322921
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: kempbd
    databaseName: kempbd
    user: kempbd_user
    plan: free 